create table CUSTOMER (
    CUSTOMER_ID INTEGER,
    DISCOUNT_CODE CHAR(1),
    ZIP VARCHAR(10),
    NAME VARCHAR(30),
    ADDRESSLINE1 VARCHAR(30),
    ADDRESSLINE2 VARCHAR(30),
    CITY VARCHAR(25),
    STATE CHAR(2),
    PHONE CHAR(12),
    FAX CHAR(12),
    EMAIL VARCHAR(40),
    CREDIT_LIMIT INTEGER
)
